version: '{build}'
platform: x64
configuration: Release
os: Visual Studio 2015
clone_depth: 50
environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - set MSYSTEM=MINGW64
  - bash -lc "pacman -Sy --noconfirm --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain git mingw-w64-i686-cmake mingw-w64-x86_64-cmake"

before_build:
  - set MSYSTEM=MINGW64
  - git clone --recursive https://github.com/cretz/tor-static c:\gopath\src\github.com\cretz\tor-static
  - cd c:\gopath\src\github.com\cretz\tor-static
  - git submodule update --init --recursive

build_script:
  - set MSYSTEM=MINGW64
  - bash --debug -lc "ls /c/gopath/src/github.com/cretz/tor-static && export PATH=/mingw64/bin:$PATH && cd /c/gopath/src/github.com/cretz/tor-static && /c/go/bin/go run build.go -verbose build-all"

after_build:
  - 7z a tor-static-windows-amd64.zip c:\gopath\src\github.com\cretz\tor-static\tor\dist\bin\*
deploy:
  provider: GitHub
  auth_token:
    secure: rpEZEcM8WsyZpn9HVmgAZ4bTKUvB+dGf0suQpQUE5CJXvX64Aq4KlHY0YRK2my21
  artifact: tor-static-windows-amd64.zip
  draft: true
  prerelease: true
  force_update: true
  release: $(APPVEYOR_REPO_TAG_NAME)
  on:
    branch: embedded-tor
    APPVEYOR_REPO_TAG: true