language: go
matrix:
  include:
    - name: linux-amd64
      os: linux
      dist: xenial
      env: CGO_ENABLED=1 GOOS=linux GOARCH=amd64
      install:
        - sudo apt-get install build-essential
        - sudo apt-get install libtool
        - sudo apt-get install autopoint
    - name: darwin-amd64
      os: osx
      env: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64
      install:
        - brew install libtool
        - brew install gettext
#    - name: windows-amd64
#      os: windows
#      env: CGO_ENABLED=1 GOOS=windows GOARCH=amd64
#      install:
#        - choco install msys2
#        - c:\tools\msys64\msys2_shell.cmd
#        - pacman -Syuu
#        - exit
#        - c:\tools\msys64\msys2_shell.cmd
#        - pacman -Sy --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain \
#          git subversion mercurial \
#          mingw-w64-i686-cmake mingw-w64-x86_64-cmake
go:
  - "1.10.3"
sudo: required
services:
  - docker
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get -u github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/tcnksm/ghr
  - go get -u github.com/cretz/tor-static github.com/cretz/bine golang.org/x/crypto/sha3 golang.org/x/net/proxy
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10
install:
  - echo "No external dependencies required. Skipping travis default library dependency setup to use vendors..."
  - sudo apt-get install openjdk-8-jre
  - cd $GOPATH/src/github.com/cretz/tor-static
  - go run build.go build-all
  - cd $TRAVIS_BUILD_DIR
script:
  - $GOPATH/bin/golangci-lint run --deadline 10m
  - cd $GOPATH/src/github.com/OpenBazaar/openbazaar-go && go test -i && ./test_compile.sh
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
after_success:
  - ./deploy.sh
