on: push
jobs:
  run_qa:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - name: Build docker image
      run: make docker
    - name: Push docker image
      run: make push_docker
