on: push
jobs:
  run_qa:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Log in to registry
      uses: actions/docker/login@master
      env:
        DOCKER_REGISTRY_URL: docker.dev.ob1.io
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: make docker
    - name: Push docker image
      run: make push_docker
